Repository apache/incubator-hugegraph, pull requests merged in 2022-12, with the labels that each got.

#2041 refact(dist): avoid script exit while restarting & clean script
  hugegraph-api/src/main/java/org/apache/hugegraph/version/ApiVersion.java
  hugegraph-core/src/main/java/org/apache/hugegraph/version/CoreVersion.java
  hugegraph-dist/src/assembly/static/bin/hugegraph
  hugegraph-dist/src/assembly/static/bin/stop-hugegraph.sh
  hugegraph-dist/src/assembly/static/bin/util.sh
Labels: shell

#2048 chore: prepare for apache v1.0.0 release
  .gitattributes
  .gitignore
  .licenserc.yaml
  BUILDING.md
  build.sh
  hugegraph-api/pom.xml
  hugegraph-api/src/main/java/org/apache/hugegraph/api/graph/VertexAPI.java
  hugegraph-cassandra/pom.xml
  hugegraph-core/pom.xml
  hugegraph-dist/pom.xml
  hugegraph-dist/scripts/apache-release.sh
  hugegraph-example/pom.xml
  hugegraph-style.xml
  hugegraph-test/pom.xml
  pom.xml
Labels: improvement, apache

#2052 fix(test): exclude binary file in clean plugin
  hugegraph-example/pom.xml
  hugegraph-test/pom.xml
Labels: ci-cd

#2053 chore: add remain 3rd-party dependency licenses
  hugegraph-dist/release-docs/NOTICE
  hugegraph-dist/release-docs/licenses/LICENSE-cassandra-all.txt
  hugegraph-dist/release-docs/licenses/LICENSE-concurrent-trees.txt
  hugegraph-dist/release-docs/licenses/LICENSE-concurrentlinkedhashmap-lru.txt
  hugegraph-dist/release-docs/licenses/LICENSE-disruptor.txt
  hugegraph-dist/release-docs/licenses/LICENSE-error-prone.txt
  hugegraph-dist/release-docs/licenses/LICENSE-exp4j.txt
  hugegraph-dist/release-docs/licenses/LICENSE-expressions-9.0.txt
  hugegraph-dist/release-docs/licenses/LICENSE-fastutil.txt
  hugegraph-dist/release-docs/licenses/LICENSE-findbugs-annotations.txt
  hugegraph-dist/release-docs/licenses/LICENSE-front-end.txt
  hugegraph-dist/release-docs/licenses/LICENSE-groovy-groovysh.txt
  hugegraph-dist/release-docs/licenses/LICENSE-groovy-json.txt
  hugegraph-dist/release-docs/licenses/LICENSE-groovy-jsr223.txt
  hugegraph-dist/release-docs/licenses/LICENSE-hamcrest.txt
  hugegraph-dist/release-docs/licenses/LICENSE-hppc.txt
  hugegraph-dist/release-docs/licenses/LICENSE-javax.json.txt
  hugegraph-dist/release-docs/licenses/LICENSE-jcabi-log.txt
  hugegraph-dist/release-docs/licenses/LICENSE-jcabi-manifests.txt
  hugegraph-dist/release-docs/licenses/LICENSE-jcl-over-slf4j.txt
  hugegraph-dist/release-docs/licenses/LICENSE-jflex.txt
  hugegraph-dist/release-docs/licenses/LICENSE-jieba-analysis.txt
  hugegraph-dist/release-docs/licenses/LICENSE-json-simple.txt
  hugegraph-dist/release-docs/licenses/LICENSE-json-smart.txt
  hugegraph-dist/release-docs/licenses/LICENSE-ohc-core.txt
  hugegraph-dist/release-docs/licenses/LICENSE-opencypher-ast-9.0.txt
  hugegraph-dist/release-docs/licenses/LICENSE-parboiled-core.txt
  hugegraph-dist/release-docs/licenses/LICENSE-parboiled-scala_2.12.txt
  hugegraph-dist/release-docs/licenses/LICENSE-parser-9.0.txt
  hugegraph-dist/release-docs/licenses/LICENSE-rewriting-9.0.txt
  hugegraph-dist/release-docs/licenses/LICENSE-rocksdbjni.txt
  hugegraph-dist/release-docs/licenses/LICENSE-sigar.txt
  hugegraph-dist/release-docs/licenses/LICENSE-snakeyaml.txt
  hugegraph-dist/release-docs/licenses/LICENSE-snowball-stemmer.txt
  hugegraph-dist/release-docs/licenses/LICENSE-tracer-core.txt
  hugegraph-dist/release-docs/licenses/LICENSE-util-9.0.txt
Labels: apache

#2060 fallback queryNumber() if there are uncommitted records
  hugegraph-core/src/main/java/org/apache/hugegraph/backend/query/Query.java
  hugegraph-core/src/main/java/org/apache/hugegraph/backend/tx/GraphTransaction.java
  hugegraph-test/src/main/java/org/apache/hugegraph/core/EdgeCoreTest.java
  hugegraph-test/src/main/java/org/apache/hugegraph/core/VertexCoreTest.java
Labels: ci-cd, tests
