Repository apache/incubator-hugegraph, pull requests merged in 2024-07, with the labels that each got.

#2585 chore: upgrade revision to 1.5.0
  hugegraph-pd/pom.xml
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/version/CoreVersion.java
  hugegraph-server/hugegraph-dist/src/assembly/travis/start-pd.sh
  hugegraph-server/hugegraph-dist/src/assembly/travis/start-store.sh
  install-dist/scripts/dependency/known-dependencies.txt
  pom.xml
Labels: size:M, lgtm

#2568 fix(server): random generate default value
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/auth/StandardAuthManager.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/config/AuthOptions.java
Labels: size:S, lgtm

#2574 chore: minor improve for pom properties
  .github/workflows/pd-store-ci.yml
  hugegraph-pd/hg-pd-client/pom.xml
  hugegraph-pd/hg-pd-common/pom.xml
  hugegraph-pd/hg-pd-dist/pom.xml
  hugegraph-pd/pom.xml
  hugegraph-server/hugegraph-dist/pom.xml
  hugegraph-server/pom.xml
  hugegraph-store/hg-store-client/pom.xml
  hugegraph-store/hg-store-dist/pom.xml
  hugegraph-store/hg-store-grpc/pom.xml
  hugegraph-store/hg-store-rocksdb/pom.xml
  hugegraph-store/hg-store-test/pom.xml
  hugegraph-store/pom.xml
  pom.xml
Labels: ci-cd, dependencies, size:L, lgtm

#2588 refact: enhance cache invalidation of the partition -> leader shard in ClientCache
  hugegraph-pd/hg-pd-client/src/main/java/org/apache/hugegraph/pd/client/ClientCache.java
  hugegraph-pd/hg-pd-client/src/main/java/org/apache/hugegraph/pd/client/PDClient.java
Labels: pd, size:XS, lgtm

#2587 doc(pd): add `initial-store-count` comments in `application.yml`
  hugegraph-pd/hg-pd-dist/src/assembly/static/conf/application.yml
Labels: pd, size:XS, lgtm

#2586 feat: support disable RocksDB auto-compaction by configuration
  hugegraph-store/hg-store-rocksdb/src/main/java/org/apache/hugegraph/rocksdb/access/RocksDBOptions.java
  hugegraph-store/hg-store-rocksdb/src/main/java/org/apache/hugegraph/rocksdb/access/RocksDBSession.java
Labels: feature, size:S, lgtm

#2590 fix(dist): update build artifact path for docker deployment
  hugegraph-pd/Dockerfile
  hugegraph-server/Dockerfile
  hugegraph-store/Dockerfile
Labels: ci-cd, size:S, lgtm

#2591 chore: intro `editorconfig-maven-plugin` for verifying code style defined in `.editorconfig`
  hugegraph-server/hugegraph-api/pom.xml
  hugegraph-server/pom.xml
  pom.xml
Labels: ci-cd, size:M, lgtm

#2596 fix(pd): partition IDs always empty in Shards List
  hugegraph-pd/hg-pd-service/src/main/java/org/apache/hugegraph/pd/rest/PartitionAPI.java
Labels: pd, size:XS, lgtm

#2599 chore: temporarily ignore failure core tests for hstore & simplify ci name
  .github/workflows/licence-checker.yml
  .github/workflows/pd-store-ci.yml
  .github/workflows/server-ci.yml
  hugegraph-pd/hg-pd-dist/pom.xml
  hugegraph-server/hugegraph-dist/pom.xml
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/EdgeCoreTest.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/MultiGraphsTest.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/RamTableTest.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/VertexCoreTest.java
  hugegraph-server/pom.xml
  hugegraph-store/hg-store-dist/pom.xml
  hugegraph-store/pom.xml
  install-dist/scripts/dependency/known-dependencies.txt
Labels: ci-cd, tests, size:L, lgtm
