Repository apache/incubator-hugegraph, pull requests merged in 2024-08, with the labels that each got.

#2609 chore: enable up-to-date for UI(CI)
  .asf.yaml
Labels: ci-cd, size:XS, lgtm

#2589 fix(pd/store): log files do not scroll with the process
  hugegraph-pd/hg-pd-dist/src/assembly/static/bin/start-hugegraph-pd.sh
  hugegraph-pd/hg-pd-service/pom.xml
  hugegraph-store/hg-store-dist/src/assembly/static/bin/start-hugegraph-store.sh
  hugegraph-store/hg-store-node/pom.xml
Labels: pd, store, size:S, lgtm

#2598 refact(pd): remove redundant property in LogMeta & PartitionMeta
  hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/meta/LogMeta.java
  hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/meta/PartitionMeta.java
  hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/meta/StoreInfoMeta.java
Labels: pd, size:XS, lgtm

#2610 doc(server): enhance rest-server.properties comment
  hugegraph-server/hugegraph-dist/src/assembly/static/conf/rest-server.properties
Labels: size:XS, lgtm

#2625 chore(pd): translate CJK punctuations to English
  hugegraph-pd/hg-pd-client/src/main/java/org/apache/hugegraph/pd/client/PDClient.java
  hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/PartitionService.java
  hugegraph-pd/hg-pd-core/src/main/java/org/apache/hugegraph/pd/StoreNodeService.java
Labels: pd, size:M, lgtm

#2623 chore(store): translate CJK comments to English for store-cli, store-client, store-common, store-core
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/StoreConsoleApplication.java
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/loader/HgThread2DB.java
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/scan/GrpcShardScanner.java
  hugegraph-store/hg-store-client/src/main/java/org/apache/hugegraph/store/HgKvStore.java
  hugegraph-store/hg-store-client/src/main/java/org/apache/hugegraph/store/client/HgNodePartition.java
  hugegraph-store/hg-store-client/src/main/java/org/apache/hugegraph/store/client/HgStoreNodePartitionerImpl.java
  hugegraph-store/hg-store-client/src/main/java/org/apache/hugegraph/store/client/NodeTxExecutor.java
  hugegraph-store/hg-store-client/src/main/java/org/apache/hugegraph/store/client/NodeTxSessionProxy.java
  hugegraph-store/hg-store-client/src/main/java/org/apache/hugegraph/store/client/grpc/GrpcStoreStreamClient.java
  hugegraph-store/hg-store-client/src/main/java/org/apache/hugegraph/store/client/grpc/GrpcUtil.java
  hugegraph-store/hg-store-client/src/main/java/org/apache/hugegraph/store/client/grpc/KvBatchScanner.java
  hugegraph-store/hg-store-client/src/main/java/org/apache/hugegraph/store/client/grpc/KvBatchScannerMerger.java
  hugegraph-store/hg-store-common/src/main/java/org/apache/hugegraph/store/term/Bits.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/HeartbeatService.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/HgStoreEngine.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/PartitionEngine.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/PartitionInstructionProcessor.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/PartitionStateListener.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/business/BusinessHandler.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/business/BusinessHandlerImpl.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/business/DataMover.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/business/DefaultDataMover.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/business/FilterIterator.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/business/InnerKeyCreator.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/business/InnerKeyFilter.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/cmd/HgCmdClient.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/cmd/HgCmdProcessor.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/GraphIdManager.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/GraphManager.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/MetadataKeyHelper.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/Partition.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/PartitionManager.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/PartitionStats.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/Shard.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/ShardGroup.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/Store.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/StoreMetadata.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/TaskManager.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/asynctask/AbstractAsyncTask.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/asynctask/AsyncTask.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/asynctask/CleanTask.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/base/MetaStoreBase.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/meta/base/PartitionMetaStore.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/options/HgStoreEngineOptions.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/options/PartitionEngineOptions.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/options/RaftRocksdbOptions.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/pd/DefaultPdProvider.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/pd/FakePdServiceProvider.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/pd/PdProvider.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/raft/HgStoreStateMachine.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/raft/RaftOperation.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/raft/RaftTaskHandler.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/snapshot/HgSnapshotHandler.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/util/HgStoreException.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/util/IpUtil.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/util/Version.java
Labels: store, size:XL, lgtm

#2616 chore(hstore): translate CJK comments to English
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/query/EdgesQueryIterator.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/query/Query.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/serializer/BinaryBackendEntry.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/serializer/BytesBuffer.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/store/BackendMutation.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/tx/SchemaTransactionV2.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/config/CoreOptions.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/io/HugeGraphSONModule.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/meta/MetaManager.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/meta/lock/EtcdDistributedLock.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/meta/managers/GraphMetaManager.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/meta/managers/TaskMetaManager.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/task/DistributedTaskScheduler.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/task/HugeTask.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/task/TaskAndResultScheduler.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/task/TaskManager.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/traversal/optimize/HugeVertexStepByBatch.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/type/HugeTableType.java
  hugegraph-server/hugegraph-hstore/src/main/java/org/apache/hugegraph/backend/store/hstore/HstoreStore.java
  hugegraph-server/hugegraph-hstore/src/main/java/org/apache/hugegraph/backend/store/hstore/HstoreTable.java
  hugegraph-server/hugegraph-hstore/src/main/java/org/apache/hugegraph/backend/store/hstore/HstoreTables.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/EdgeCoreTest.java
Labels: size:L, lgtm

#2622 refact(server): enlarge bytes write limit & remove param `big` when encode/decode string id length
  .asf.yaml
  hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/AccessLogFilter.java
  hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/core/GraphManager.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/cache/OffheapCache.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/id/Id.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/serializer/BinarySerializer.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/serializer/BytesBuffer.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/structure/HugeEdge.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/structure/HugeElement.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/task/HugeTask.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/EdgeCoreTest.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/VertexCoreTest.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/unit/cache/CacheTest.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/unit/id/IdUtilTest.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/unit/serializer/BytesBufferTest.java
Labels: size:L, lgtm

#2630 fix(hstore): JRaft maxEntriesSize configuration parameters do not take effect
  .asf.yaml
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/options/HgStoreEngineOptions.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/AppConfig.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/HgStoreNodeService.java
Labels: store, size:S, lgtm

#2637 fix: correct server docker copy source path
  hugegraph-server/Dockerfile
Labels: bug, size:XS, lgtm

#2636 fix(hstore): enhance hstore gc log
  hugegraph-store/hg-store-dist/src/assembly/static/bin/start-hugegraph-store.sh
Labels: store, size:XS, lgtm

#2633 fix(hstore): enable JRaft MaxBodySize config
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/PartitionEngine.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/options/HgStoreEngineOptions.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/AppConfig.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/HgStoreNodeService.java
Labels: raft, store, size:S, lgtm

#2646 chore(ci): disable merge button & rename ci job name
  .asf.yaml
  .github/workflows/server-ci.yml
Labels: ci-cd, size:XS, lgtm

#2645 chore(store): translate CJK comments to English for store-dist, store-grpc, store-node, store-rocksdb, store-test
  hugegraph-store/hg-store-dist/src/assembly/static/bin/start-hugegraph-store.sh
  hugegraph-store/hg-store-dist/src/assembly/static/conf/application-pd.yml
  hugegraph-store/hg-store-dist/src/assembly/static/conf/application.yml
  hugegraph-store/hg-store-grpc/pom.xml
  hugegraph-store/hg-store-grpc/src/main/proto/graphpb.proto
  hugegraph-store/hg-store-grpc/src/main/proto/store_common.proto
  hugegraph-store/hg-store-grpc/src/main/proto/store_session.proto
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/AppConfig.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/AppShutdownHook.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/StoreNodeApplication.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/controller/HgTestController.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/controller/PartitionAPI.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/BatchGrpcClosure.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/GrpcClosure.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/HgStoreNodeService.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/HgStoreSessionImpl.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/HgStoreWrapperEx.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/ParallelScanIterator.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/ScanBatchResponse.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/ScanBatchResponseFactory.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/ScanUtil.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/scan/GraphStoreImpl.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/scan/ScanResponseObserver.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/listener/PdConfigureListener.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/util/HgGrpc.java
  hugegraph-store/hg-store-node/src/main/resources/application-pd.yml
  hugegraph-store/hg-store-node/src/main/resources/application.yml
  hugegraph-store/hg-store-node/src/test/java/org/apache/hugegraph/store/node/HgStoreNodeServiceTest.java
  hugegraph-store/hg-store-node/src/test/resources/application-pd.yml
  hugegraph-store/hg-store-node/src/test/resources/application-server00.yml
  hugegraph-store/hg-store-node/src/test/resources/application-server01.yml
  hugegraph-store/hg-store-node/src/test/resources/application-server02.yml
  hugegraph-store/hg-store-node/src/test/resources/application-server03.yml
  hugegraph-store/hg-store-node/src/test/resources/application-server04.yml
  hugegraph-store/hg-store-node/src/test/resources/application-server05.yml
  hugegraph-store/hg-store-node/src/test/resources/application-server06.yml
  hugegraph-store/hg-store-rocksdb/src/main/java/org/apache/hugegraph/rocksdb/access/RocksDBFactory.java
  hugegraph-store/hg-store-rocksdb/src/main/java/org/apache/hugegraph/rocksdb/access/RocksDBSession.java
  hugegraph-store/hg-store-rocksdb/src/main/java/org/apache/hugegraph/rocksdb/access/SessionOperator.java
  hugegraph-store/hg-store-rocksdb/src/main/java/org/apache/hugegraph/rocksdb/access/SessionOperatorImpl.java
  hugegraph-store/hg-store-test/src/main/java/org/apache/hugegraph/store/HgSessionManagerOneRaftFakePDTest.java
  hugegraph-store/hg-store-test/src/main/java/org/apache/hugegraph/store/HgSessionManagerRaftFakePDTest.java
  hugegraph-store/hg-store-test/src/main/java/org/apache/hugegraph/store/HgSessionManagerRaftPDTest.java
  hugegraph-store/hg-store-test/src/main/java/org/apache/hugegraph/store/HgSessionManagerTest.java
  hugegraph-store/hg-store-test/src/main/java/org/apache/hugegraph/store/PartitionEngineTest.java
  hugegraph-store/hg-store-test/src/main/java/org/apache/hugegraph/store/client/ChangeShardNumTest.java
  hugegraph-store/hg-store-test/src/main/java/org/apache/hugegraph/store/client/HgSessionManagerRaftPDTest.java
  hugegraph-store/hg-store-test/src/main/java/org/apache/hugegraph/store/core/CoreSuiteTest.java
  hugegraph-store/hg-store-test/src/main/java/org/apache/hugegraph/store/core/HgCmdClientTest.java
  hugegraph-store/hg-store-test/src/main/java/org/apache/hugegraph/store/core/StoreEngineTestBase.java
  hugegraph-store/hg-store-test/src/main/resources/pd-server.yml
Labels: store, size:L, lgtm

#2647 feat(common): add a tool method encode
  hugegraph-commons/hugegraph-common/src/main/java/org/apache/hugegraph/rest/AbstractRestClient.java
  hugegraph-commons/hugegraph-common/src/test/java/org/apache/hugegraph/unit/UnitTestSuite.java
  hugegraph-commons/hugegraph-common/src/test/java/org/apache/hugegraph/unit/rest/AbstractRestClientTest.java
Labels: feature, size:M, lgtm

#2643 chore(ci): fix postgresql unit test failed
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/TaskCoreTest.java
Labels: bug, ci-cd, size:XS, lgtm
