Repository apache/incubator-hugegraph, pull requests merged in 2024-11, with the labels that each got.

#2649 feat(server): support MemoryManagement for graph query framework
  hugegraph-server/hugegraph-core/pom.xml
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/StandardHugeGraph.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/cache/CachedBackendStore.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/id/EdgeId.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/id/IdGenerator.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/serializer/BinaryBackendEntry.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/config/CoreOptions.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/MemoryManager.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/allocator/MemoryAllocator.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/allocator/NettyMemoryAllocator.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/allocator/OnHeapMemoryAllocator.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/arbitrator/MemoryArbitrator.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/arbitrator/MemoryArbitratorImpl.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/consumer/OffHeapObject.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/consumer/factory/IdFactory.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/consumer/factory/PropertyFactory.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/consumer/impl/id/BinaryIdOffHeap.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/consumer/impl/id/EdgeIdOffHeap.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/consumer/impl/id/LongIdOffHeap.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/consumer/impl/id/ObjectIdOffHeap.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/consumer/impl/id/QueryIdOffHeap.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/consumer/impl/id/StringIdOffHeap.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/consumer/impl/id/UuidIdOffHeap.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/consumer/impl/property/HugeEdgePropertyOffHeap.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/consumer/impl/property/HugeVertexPropertyOffHeap.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/pool/AbstractMemoryPool.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/pool/MemoryPool.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/pool/impl/MemoryPoolStats.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/pool/impl/OperatorMemoryPool.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/pool/impl/QueryMemoryPool.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/pool/impl/TaskMemoryPool.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/util/FurySerializationUtil.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/util/OffHeapMemoryUtil.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/util/OutOfMemoryException.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/util/RoundUtil.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/memory/util/SerializationRuntimeException.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/structure/HugeProperty.java
  hugegraph-server/hugegraph-dist/src/assembly/static/conf/graphs/hugegraph.properties
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/memory/MemoryAllocateTest.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/memory/MemoryConsumerTest.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/memory/MemoryManageTest.java
  install-dist/scripts/dependency/known-dependencies.txt
Labels: feature, size:XXL, lgtm

#2569 fix(server): Filter dynamice path(PUT/GET/DELETE) with params cause OOM
  hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/filter/AccessLogFilter.java
Labels: bug, size:M, lgtm

#2631 fix(hstore): JRaft Histogram Metrics Value NaN
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/metrics/JRaftMetrics.java
Labels: bug, store, size:M, lgtm

#2690 chore(dist): update outdated docs for release 1.5.0
  README.md
  hugegraph-server/hugegraph-dist/docker/README.md
Labels: size:S, lgtm

#2692 chore(dist): fix licenses and remove empty files
  .gitattributes
  hugegraph-store/hg-store-rocksdb/src/main/java/place-holder.txt
  hugegraph-store/hg-store-rocksdb/src/test/java/place-holder.txt
  install-dist/release-docs/LICENSE
  install-dist/release-docs/licenses/LICENSE-aopalliance-repackaged-3.0.1.txt
  install-dist/release-docs/licenses/LICENSE-grizzly-framework-3.0.1.txt
  install-dist/release-docs/licenses/LICENSE-grizzly-http-3.0.1.txt
  install-dist/release-docs/licenses/LICENSE-grizzly-http-server-3.0.1.txt
  install-dist/release-docs/licenses/LICENSE-hk2-api-3.0.1.txt
  install-dist/release-docs/licenses/LICENSE-hk2-locator-3.0.1.txt
  install-dist/release-docs/licenses/LICENSE-hk2-utils-3.0.1.txt
  install-dist/release-docs/licenses/LICENSE-jakarta.annotation-api-1.3.5.txt
  install-dist/release-docs/licenses/LICENSE-jakarta.annotation-api-2.0.0.txt
  install-dist/release-docs/licenses/LICENSE-jakarta.websocket-api-1.1.2.txt
  install-dist/release-docs/licenses/LICENSE-jakarta.ws.rs-api-3.0.0.txt
  install-dist/release-docs/licenses/LICENSE-javax.activation-api-1.2.0.txt
  install-dist/release-docs/licenses/LICENSE-javax.annotation-api-1.3.2.txt
  install-dist/release-docs/licenses/LICENSE-jaxb-api-2.3.1.txt
  install-dist/release-docs/licenses/LICENSE-jersey-apache-connector-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-client-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-common-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-container-grizzly2-http-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-container-grizzly2-servlet-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-container-servlet-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-container-servlet-core-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-entity-filtering-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-hk2-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-media-jaxb-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-media-json-jackson-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-server-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-test-framework-core-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jersey-test-framework-provider-grizzly2-3.0.3.txt
  install-dist/release-docs/licenses/LICENSE-jna-5.12.1.txt
  install-dist/release-docs/licenses/LICENSE-jna-5.5.0.txt
  install-dist/release-docs/licenses/LICENSE-jna-5.7.0.txt
  install-dist/release-docs/licenses/LICENSE-lucene-analyzers-common-8.11.2.txt
  install-dist/release-docs/licenses/LICENSE-lucene-analyzers-smartcn-8.11.2.txt
  install-dist/release-docs/licenses/LICENSE-lucene-core-8.11.2.txt
  install-dist/release-docs/licenses/LICENSE-lucene-queries-4.7.2.txt
  install-dist/release-docs/licenses/LICENSE-lucene-queryparser-4.7.2.txt
  install-dist/release-docs/licenses/LICENSE-lucene-sandbox-4.7.2.txt
  install-dist/release-docs/licenses/LICENSE-swagger-annotations-1.5.18.txt
  install-dist/release-docs/licenses/LICENSE-swagger-models-1.5.18.txt
Labels: size:XS, lgtm

#2695 docs: update repo artifacts references
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: size:XS, lgtm

#2697 chore(dist): fix the JSON license issue
  hugegraph-store/hg-store-core/pom.xml
  install-dist/release-docs/LICENSE
  install-dist/release-docs/licenses/LICENSE-json-20210307.txt
  install-dist/scripts/dependency/known-dependencies.txt
Labels: size:M, lgtm
