Repository apache/incubator-hugegraph, pull requests merged in 2024-01, with the labels that each got.

#2398 chore: add license link
  README.md
Labels: lgtm

#2409 doc: enhance NOTICE info to keep it clear
  .github/workflows/check-dependencies.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/licence-checker.yml
  NOTICE
  hugegraph-server/hugegraph-dist/release-docs/NOTICE
Labels: ci-cd, size:L, lgtm

#2403 feat: support docker use the auth when starting
  .licenserc.yaml
  LICENSE
  README.md
  hugegraph-server/hugegraph-dist/docker/README.md
  hugegraph-server/hugegraph-dist/docker/docker-entrypoint.sh
  hugegraph-server/hugegraph-dist/docker/example/docker-compose-cassandra.yml
  hugegraph-server/hugegraph-dist/download_keystore.sh
  hugegraph-server/hugegraph-dist/download_swagger_ui.sh
  hugegraph-server/hugegraph-dist/pom.xml
  hugegraph-server/hugegraph-dist/release-docs/LICENSE
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/enable-auth.sh
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/gremlin-console.sh
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/util.sh
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/wait-storage.sh
Labels: feature, ci-cd, size:L, lgtm

#2417 chore(docker): cherry-pick commits from master for fix some error when using docker image for 1.2.0 as #2403
  .licenserc.yaml
  LICENSE
  README.md
  hugegraph-server/hugegraph-dist/docker/README.md
  hugegraph-server/hugegraph-dist/docker/docker-entrypoint.sh
  hugegraph-server/hugegraph-dist/docker/example/docker-compose-cassandra.yml
  hugegraph-server/hugegraph-dist/download_keystore.sh
  hugegraph-server/hugegraph-dist/download_swagger_ui.sh
  hugegraph-server/hugegraph-dist/pom.xml
  hugegraph-server/hugegraph-dist/release-docs/LICENSE
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/enable-auth.sh
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/gremlin-console.sh
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/util.sh
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/wait-storage.sh
Labels: bug, ci-cd, cassandra, size:L, lgtm

#2411 fix(server): reinitialize the progress to set up graph auth friendly
  hugegraph-server/hugegraph-dist/src/main/java/org/apache/hugegraph/cmd/InitStore.java
Labels: bug, feature, tests, size:XS, lgtm

#2419 fix(server): starting error of hgServer
  hugegraph-server/hugegraph-dist/scripts/dependency/known-dependencies.txt
  hugegraph-server/pom.xml
  pom.xml
Labels: bug, ci-cd, size:M

#2421 fix(chore): remove zgc in dockerfile for ARM env
  hugegraph-server/Dockerfile
  hugegraph-server/hugegraph-dist/docker/docker-entrypoint.sh
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/enable-auth.sh
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/hugegraph-server.sh
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/util.sh
Labels: bug, ci-cd, size:M, lgtm

#2423 chore(server): update swagger info for default server profile
  hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/profile/ProfileAPI.java
Labels: api, size:XS, lgtm

#2427 chore(docker): cherry-pick commits from master to remove zgc in dockerfile for ARM env as #2421
  hugegraph-server/Dockerfile
  hugegraph-server/hugegraph-dist/docker/docker-entrypoint.sh
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/enable-auth.sh
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/hugegraph-server.sh
  hugegraph-server/hugegraph-dist/src/assembly/static/bin/util.sh
Labels: ci-cd, size:M, lgtm

#2424 fix(pd-store): partially fix hstore backend core tests failure
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/serializer/BinaryBackendEntry.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/serializer/BinarySerializer.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/tx/SchemaTransactionV2.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/EdgeCoreTest.java
  hugegraph-server/hugegraph-test/src/main/java/org/apache/hugegraph/core/VertexCoreTest.java
Labels: bug, tests, size:M, hstore
