Repository apache/incubator-hugegraph, pull requests merged in 2024-12, with the labels that each got.

#2702 fix(docker): update server image desc
  README.md
  hugegraph-server/hugegraph-dist/docker/README.md
Labels: size:S, lgtm

#2699 fix(server): kneigbor-api has unmatched edge type with server
  hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/api/traversers/KneighborAPI.java
Labels: bug, api, size:S, lgtm

#2688 chore: add debug info for tp test
  .github/workflows/server-ci.yml
Labels: ci-cd, inactive, size:XS

#2706 fix(dist): add license for swagger-ui & reset use stage to false in ci yml
  .github/workflows/check-dependencies.yml
  .github/workflows/cluster-test-ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/commons-ci.yml
  .github/workflows/licence-checker.yml
  .github/workflows/pd-store-ci.yml
  .github/workflows/server-ci.yml
  install-dist/release-docs/LICENSE
Labels: size:M, lgtm
