Repository apache/incubator-hugegraph, pull requests merged in 2025-09, with the labels that each got.

#2861 perf(core): optimize perf by avoid boxing long
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/query/Condition.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/query/Query.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/backend/serializer/BytesBuffer.java
Labels: perf, size:L, lgtm

#2860 perf(example): add PerfExample5 and PerfExample6
  hugegraph-server/hugegraph-example/src/main/java/org/apache/hugegraph/example/PerfExample1.java
  hugegraph-server/hugegraph-example/src/main/java/org/apache/hugegraph/example/PerfExample2.java
  hugegraph-server/hugegraph-example/src/main/java/org/apache/hugegraph/example/PerfExample4.java
  hugegraph-server/hugegraph-example/src/main/java/org/apache/hugegraph/example/PerfExample5.java
  hugegraph-server/hugegraph-example/src/main/java/org/apache/hugegraph/example/PerfExample6.java
  hugegraph-server/hugegraph-example/src/main/java/org/apache/hugegraph/example/PerfExampleBase.java
Labels: perf, size:L, lgtm

#2863 perf(rocksdb): RocksDBStore remove redundant checkOpened() call
  hugegraph-server/hugegraph-rocksdb/src/main/java/org/apache/hugegraph/backend/store/rocksdb/RocksDBStore.java
Labels: perf, store, size:M, lgtm

#2874 chore: improve maven Reproducible Builds → upgrade plugins
  hugegraph-cluster-test/hugegraph-clustertest-dist/pom.xml
  hugegraph-pd/hg-pd-dist/pom.xml
  hugegraph-pd/hg-pd-service/pom.xml
  hugegraph-server/hugegraph-core/pom.xml
  hugegraph-server/hugegraph-dist/pom.xml
  hugegraph-store/hg-store-cli/pom.xml
  hugegraph-store/hg-store-dist/pom.xml
  hugegraph-store/hg-store-node/pom.xml
  pom.xml
Labels: ci-cd, size:S, lgtm

#2792 refactor: remove the package existing in java8
  hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/auth/HugeFactoryAuthProxy.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/security/HugeSecurityManager.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/util/Reflection.java
Labels: inactive, size:M, lgtm

#2882 docs: revise Docker usage instructions in README
  README.md
Labels: size:XS, lgtm
