Repository apache/incubator-hugegraph, pull requests merged in 2025-07, with the labels that each got.

#2824 fix(server): ensure backend is initialized in gremlin script
  hugegraph-server/hugegraph-dist/src/assembly/static/scripts/example.groovy
Labels: bug, size:XS, lgtm

#2826 chore: update notice year
  NOTICE
Labels: size:XS, lgtm

#2843 feat(server): add option for task role election
  hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/config/ServerOptions.java
  hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/core/GraphManager.java
  hugegraph-server/hugegraph-core/src/main/java/org/apache/hugegraph/task/TaskManager.java
Labels: feature, size:M, lgtm
